# Generated by Django 4.1 on 2023-10-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkuapi', '0002_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
