# Generated by Django 4.1 on 2024-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkuapi', '0004_alter_student_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
    ]
