# Generated by Django 4.1 on 2023-10-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0002_alter_feesstructure_balance_alter_feesstructure_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='regno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='balance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='fees',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='payment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
