# Generated by Django 4.1 on 2023-11-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkuapi', '0003_alter_student_contact_alter_student_course_and_more'),
        ('fees_structure', '0003_feesstructure_regno_alter_feesstructure_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mkuapi.student'),
        ),
    ]
