# Generated by Django 4.1 on 2023-11-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_structure', '0004_feesstructure_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='student',
        ),
    ]
