# Generated by Django 4.1 on 2023-11-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkuapi', '0004_alter_student_regno'),
        ('fees_structure', '0008_remove_feesstructure_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mkuapi.student'),
        ),
    ]
