# Generated by Django 4.1 on 2024-01-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkuapi', '0005_student_role'),
        ('fees_structure', '0010_alter_feesstructure_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesstructure',
            old_name='balance',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='feesstructure',
            old_name='date_reg',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='regno',
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mkuapi.student'),
        ),
    ]
